#
# Module manifest for module 'Pulse'
#
# Generated by: Justin Grote github:@JustinGrote bsky:@posh.guru
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Pulse.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

# Author of this module
Author = 'Justin Grote github:@JustinGrote bsky:@posh.guru'

# Company or vendor of this module
CompanyName = 'Pulse'

# Copyright statement for this module
Copyright = '(c) 2026 Justin Grote. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for monitoring and reporting on scripts using OpenTelemetry'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @('Trace-PulseCommand')

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'OpenTelemetry', 'Telemetry', 'Tracing', 'Monitoring', 'Observability'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/JustinGrote/Pulse/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/JustinGrote/Pulse'

        # Prerelease string of this module
        Prerelease = 'alpha'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
